version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: cinema_nginx
    depends_on:
      - app
    volumes:
      - ./:/var/www
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '${DOCKER_NGINX_EXTERNAL_PORT}:80'
    networks:
      - default
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: cinema_app
    depends_on:
      - db
    volumes:
      - ./:/var/www
    expose:
      - '9000'
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    networks:
      - default
  db:
    image: mariadb:10.4
    container_name: cinema_mysql
    tty: true
    ports:
      - '${DOCKER_MYSQL_EXTERNAL_PORT}:3306'
    environment:
      MYSQL_DATABASE: cinema-php
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev==
      MYSQL_ROOT_PASSWORD: dev==
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - mysql-db:/var/lib/mysql/
      - ./docker/mysql/init:/docker-entrypoint-initdb.d/:ro #init database dev user
    command: mysqld --sql_mode=""
    networks:
      - default

volumes:
  mysql-db:
    driver: local
networks:
  default:
    driver: bridge
